spring.datasource:
  url: jdbc:mysql://120.77.204.36:3306/insurance_wbad?characterEncoding=UTF-8&allowMultiQueries=true
  username: hlb_user
  password: rldb123@
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.mysql.jdbc.Driver
  maxActive: 20
  initialSize: 1
  maxWait: 60000
  minIdle: 1
  hikari:
   connectionTimeout: 30000
   idleTimeout: 600000
   maxLifetime: 1800000
   maximumPoolSize: 50
   minimumIdle: 10
   validationTimeout: 5000