spring.datasource:
  url: jdbc:mysql://mysql:3306/inuurance_wbad?characterEncoding=UTF-8&allowMultiQueries=true
  username: wbadadmin
  password: wbad_admin@#987654
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.mysql.jdbc.Driver
  maxActive: 20
  initialSize: 1
  maxWait: 60000
  minIdle: 1
  hikari:
   connectionTimeout: 30000
   idleTimeout: 600000
   maxLifetime: 1800000
   maximumPoolSize: 50
   minimumIdle: 10
   validationTimeout: 5000
rsa.json:
   aeskey: fe96b52790adaefe
spring.fileupload.config:
   basepath: /opt/imagesdata
   domain: http://vivaimage.hedu.mobi